/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import Entidades.Mascota;
import Entidades.Publicacion;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.JTextComponent;


/**
 *
 * @author piero
 */
public class FrameCrearPublicación extends javax.swing.JFrame {

    private FramePublicaciones padre;
    public String tipo;
    private byte[] imagenBytes;
    /**
     * Creates new form FrameCrearPublicación
     */
    public FrameCrearPublicación() {
        initComponents();
        this.padre = padre;
                this.setLocationRelativeTo(null);

    }
    public FrameCrearPublicación(FramePublicaciones padre, String tipo) {
        initComponents();
        this.padre = padre;
        agregarTextPrompt("Nombre",txtNombre);
        agregarTextPrompt("Raza",txtRaza);
        agregarTextPrompt("Descripción",txtDescripcion);
        
        this.tipo = tipo;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtDescripcion = new javax.swing.JTextField();
        txtRaza = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnChangeImage = new javax.swing.JLabel();
        lblPetPhoto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameCrearPublicación/Group 12 (3).png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameCrearPublicación/Group 12 (3).png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameCrearPublicación/Group 22 (2).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, -1, -1));

        txtDescripcion.setBackground(new java.awt.Color(235, 235, 235));
        txtDescripcion.setBorder(null);
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 375, 330, 90));

        txtRaza.setBackground(new java.awt.Color(235, 235, 235));
        txtRaza.setBorder(null);
        jPanel1.add(txtRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 324, 330, 30));

        txtNombre.setBackground(new java.awt.Color(235, 235, 235));
        txtNombre.setBorder(null);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 274, 330, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameCrearPublicación/TextField.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 320, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameCrearPublicación/btnBack.png"))); // NOI18N
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 26, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameCrearPublicación/TextField2.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 370, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameCrearPublicación/TextField.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 270, -1, -1));

        btnChangeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameCrearPublicación/CameraPhoto.png"))); // NOI18N
        btnChangeImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangeImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangeImageMouseClicked(evt);
            }
        });
        jPanel1.add(btnChangeImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        lblPetPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameCrearPublicación/PetPhoto.png"))); // NOI18N
        jPanel1.add(lblPetPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 75, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrameCrearPublicación/FrameCrearPublicación.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 466, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Publicacion getDatos() throws NumberFormatException {
        String nombre = txtNombre.getText();
        String raza = txtRaza.getText();
        String descripcion = txtDescripcion.getText();
        
        Mascota mascota =
                new Mascota(nombre, raza, descripcion, imagenBytes);
        
        Publicacion publicacion = new Publicacion(tipo, mascota);
        return publicacion;
    }
    
    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        
        
        this.padre.setLocationRelativeTo(this);
        this.padre.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnChangeImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeImageMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home") + "\\Documents"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de imagen", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            try {
                // Cargar la imagen desde el archivo y mostrarla en el JLabel
                ImageIcon originalIcon = new ImageIcon(selectedFile.getAbsolutePath());
                Image originalImage = originalIcon.getImage();

                // Escalar la imagen al tamaño deseado (168 x 168) manteniendo la relación de aspecto
                Image scaledImage = originalImage.getScaledInstance(168, 168, Image.SCALE_SMOOTH);

                // Crear un nuevo ImageIcon con la imagen escalada
                ImageIcon scaledIcon = new ImageIcon(scaledImage);

                // Asignar el nuevo ImageIcon al JLabel
                lblPetPhoto.setIcon(scaledIcon);

                // Leer la imagen como un arreglo de bytes y asignarla a imagenBytes
                FileInputStream inputStream = new FileInputStream(selectedFile);
                imagenBytes = new byte[(int) selectedFile.length()];
                inputStream.read(imagenBytes);
                inputStream.close();

                JOptionPane.showMessageDialog(this, "Imagen cargada exitosamente. Puedes publicarla cuando lo desees.");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al cargar la imagen: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnChangeImageMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = txtNombre.getText();
        String raza = txtRaza.getText();
        String descripcion = txtDescripcion.getText();
        if (nombre.isEmpty() || raza.isEmpty() || descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Complete todo los casilleros");
            return; // No continuamos si los campos están vacíos
        }
        // Obtener los bytes de la imagen
        byte[] imagenBytes = this.imagenBytes;
        Publicacion publicacionSelec = getDatos();
        FramePublicaciones publicaciones = new FramePublicaciones(publicacionSelec);
        publicaciones.setLocationRelativeTo(null);
        publicaciones.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
 
    private static void guardarImagenEnBD(byte[] imagenBytes) throws SQLException {
        String url = "xd";
        String usuario = "tu_usuario";
        String contraseña = "tu_contraseña";

        try (Connection conexion = DriverManager.getConnection(url, usuario, contraseña)) {
            String sql = "INSERT INTO tabla_imagenes (nombre, imagen) VALUES (?, ?)";
            try (PreparedStatement pstmt = conexion.prepareStatement(sql)) {
                pstmt.setString(1, "nombre_imagen");  // Puedes cambiar esto según tus necesidades
                pstmt.setBytes(2, imagenBytes);
                pstmt.executeUpdate();
            }
        }
    }
    private void agregarTextPrompt(String placeholder, JTextComponent component) {
        TextPrompt prompt = new TextPrompt(placeholder, component); 
    }
    
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCrearPublicación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCrearPublicación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCrearPublicación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCrearPublicación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCrearPublicación().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnChangeImage;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPetPhoto;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRaza;
    // End of variables declaration//GEN-END:variables
}
