/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import Entidades.Mascota;
import Entidades.Publicacion;
import java.awt.Image;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author piero
 */
public class FramePublicaciones extends javax.swing.JFrame {

    public Publicacion publicacion;
    public Publicacion publicacionSelec;
    public static List<Publicacion> publicaciones = new ArrayList<Publicacion>();
    /**
     * Creates new form FramePublicaciones
     */
    public FramePublicaciones() {
        initComponents();
                this.setLocationRelativeTo(null);

    }

    public FramePublicaciones(Publicacion publicacion) {
        initComponents();
        this.publicacion = publicacion;
        agregarPublicacion(publicacion);
        llenarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        spPublicacion = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPublicaciones = new javax.swing.JList<>();
        btnVer = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnCrearPublicacion = new javax.swing.JLabel();
        btnMascotasPerdidas = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JLabel();
        btnAdopcion = new javax.swing.JLabel();
        lblLogoPerfil = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lstPublicaciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(lstPublicaciones);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 590, 470));

        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFramePublicaciones/Group 24.png"))); // NOI18N
        btnVer.setBorder(null);
        btnVer.setBorderPainted(false);
        btnVer.setContentAreaFilled(false);
        btnVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVer.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFramePublicaciones/Group 24.png"))); // NOI18N
        btnVer.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFramePublicaciones/Group 23.png"))); // NOI18N
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        jPanel2.add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, -1, -1));

        spPublicacion.setViewportView(jPanel2);

        jPanel1.add(spPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 72, 644, 568));

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Mascotas Perdidas");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 0, 644, 72));

        btnCrearPublicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFramePublicaciones/btnCrearPublicacion.png"))); // NOI18N
        btnCrearPublicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearPublicacionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCrearPublicacionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCrearPublicacionMouseReleased(evt);
            }
        });
        jPanel1.add(btnCrearPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        btnMascotasPerdidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFramePublicaciones/btnMascotasPerdidas.png"))); // NOI18N
        btnMascotasPerdidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMascotasPerdidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMascotasPerdidasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMascotasPerdidasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMascotasPerdidasMouseReleased(evt);
            }
        });
        jPanel1.add(btnMascotasPerdidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFramePublicaciones/btnCerrarSesion.png"))); // NOI18N
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseReleased(evt);
            }
        });
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, -1, -1));

        btnAdopcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFramePublicaciones/btnAdopcion.png"))); // NOI18N
        btnAdopcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdopcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdopcionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAdopcionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAdopcionMouseReleased(evt);
            }
        });
        jPanel1.add(btnAdopcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, -1));

        lblLogoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFramePublicaciones/image 14.png"))); // NOI18N
        jPanel1.add(lblLogoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFramePublicaciones/FramePublicaciones.png"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void agregarPublicacion(Publicacion publicacion){
        publicaciones.add(publicacion);
    }
    
    public void llenarLista(){
        DefaultListModel modelo =new DefaultListModel();        
        lstPublicaciones.setModel(modelo); 
        modelo.removeAllElements();
        for (int i = 0; i < publicaciones.size(); i++) {
            modelo.addElement(publicaciones.get(i).getTipo()+"          "
            +publicaciones.get(i).getMascota().getNombre()+"          "
            +publicaciones.get(i).getMascota().getRaza());
        }
    }
    
    private void btnAdopcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdopcionMouseClicked
        abrirPantalla("ADOPCIÓN");
    }//GEN-LAST:event_btnAdopcionMouseClicked

    private void btnAdopcionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdopcionMousePressed
        btnAdopcion.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/ImagenesFramePublicaciones/btnAdopcion2.png"))
        );
    }//GEN-LAST:event_btnAdopcionMousePressed

    private void btnAdopcionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdopcionMouseReleased
        btnAdopcion.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/ImagenesFramePublicaciones/btnAdopcion.png"))
        );
    }//GEN-LAST:event_btnAdopcionMouseReleased

    private void btnMascotasPerdidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMascotasPerdidasMouseClicked
        abrirPantalla("PERDIDO");
    }//GEN-LAST:event_btnMascotasPerdidasMouseClicked

    private void btnMascotasPerdidasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMascotasPerdidasMousePressed
        btnMascotasPerdidas.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/ImagenesFramePublicaciones/btnMascotasPerdidas2.png"))
        );
    }//GEN-LAST:event_btnMascotasPerdidasMousePressed

    private void btnMascotasPerdidasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMascotasPerdidasMouseReleased
        btnMascotasPerdidas.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/ImagenesFramePublicaciones/btnMascotasPerdidas.png"))
        );
    }//GEN-LAST:event_btnMascotasPerdidasMouseReleased

    private void btnCrearPublicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearPublicacionMouseClicked
        
    }//GEN-LAST:event_btnCrearPublicacionMouseClicked

    private void btnCrearPublicacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearPublicacionMousePressed
      
    }//GEN-LAST:event_btnCrearPublicacionMousePressed

    private void btnCrearPublicacionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearPublicacionMouseReleased
        
        
    }//GEN-LAST:event_btnCrearPublicacionMouseReleased

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        FrameIngresar login = new FrameIngresar();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void btnCerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMousePressed
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/ImagenesFramePublicaciones/btnCerrarSesion2.png"))
        );
    }//GEN-LAST:event_btnCerrarSesionMousePressed

    private void btnCerrarSesionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseReleased
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/ImagenesFramePublicaciones/btnCerrarSesion.png"))
        );
    }//GEN-LAST:event_btnCerrarSesionMouseReleased

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        int index = lstPublicaciones.getSelectedIndex();
        publicacionSelec = publicaciones.get(index);
        FrameVerPublicacion ver = new FrameVerPublicacion(publicacionSelec);
        ver.setLocationRelativeTo(null);
        ver.setVisible(true);
    }//GEN-LAST:event_btnVerActionPerformed

    private void abrirPantalla(String tipo) {
        FrameCrearPublicación pantalla = new FrameCrearPublicación(this, tipo);
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePublicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePublicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePublicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePublicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdopcion;
    private javax.swing.JLabel btnCerrarSesion;
    private javax.swing.JLabel btnCrearPublicacion;
    private javax.swing.JLabel btnMascotasPerdidas;
    private javax.swing.JButton btnVer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogoPerfil;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> lstPublicaciones;
    private javax.swing.JScrollPane spPublicacion;
    // End of variables declaration//GEN-END:variables
}
